name: iosApp
options:
  bundleIdPrefix: com.quizedguy.genghealth
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.quizedguy.genghealth
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    dependencies:
      - framework: ../shared/build/XCFrameworks/release/Shared.xcframework
        embed: true
